### PR TITLE
Include a Python stub file for the `interrogatedb` module

### PR DESCRIPTION
**Pull request by WMOkiishi**
These changes add a Python stub file for the `interrogatedb` module, allowing type-checkers and other code analysis tools to know what's contained within it. The stub will have to be manually updated whenever the module is changed, but this happens infrequently enough that it shouldn't be too much of an additional burden.

### CODE REVIEW

**Comment by rdb** [comment]
Did you create the stub file manually? Is the idea that we manually update this every time we update the API? Or can we auto-generate it using a script?

It's called `interrogatedb/__init__.pyi`, but interrogatedb is not a package, is that not misleading? Should it not just be `interrogatedb.pyi`?

**Comment by WMOkiishi** [comment]
Yes, the idea was to manually update the stub. Would auto-generating it require hooking into the interface-making system? I didn't see any database files generated like they are for Panda3D proper.

The file structure is perhaps slightly misleading, but I don't see a configuration option for scikit-build to include a top-level file in a wheel.

**Comment by rdb** [comment]
Manual is fine for now, I suppose.

If it can't be copied directly from the source directory by scikit-build, perhaps it can just be copied alongside the .pyd/.so into the site-packages dir via CMake?

**Comment by WMOkiishi** [comment]
Yup, using CMake works.

I agree that automating the generation of the stub file would be preferable and worth looking into in the future.

**Pull request merged**
